apiVersion: v1
kind: Secret
metadata:
  name: data-processing-ms-secret
  namespace: default
type: Opaque
data:
  DB_USER: c2E=
  DB_PASSWORD: TU_PASSWORD_DB_BASE64
  DB_SERVER: TU_SERVIDOR_DB_BASE64
  DB_DATABASE: TU_BASE_DE_DATOS_DB_BASE64
  DB_PORT: TU_PUERTO_DB_BASE64
  DB_ENCRYPT: dHJ1ZQ==
