apiVersion: v1
kind: Service
metadata:
  name: data-processing-ms-service
  namespace: default
  labels:
    app: data-processing-ms
spec:
  type: NodePort
  selector:
    app: data-processing-ms
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30080
